- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: git@github.com:lbarzi/Hello_World.git
      repository_path: /home/vagrant/Hello_World

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python3-pip
        - nginx

    - name: Clone repository
      git:
        repo: "git@github.com:lbarzi/Hello_World.git"
        dest: /home/vagrant/Hello_World
        key_file: /home/vagrant/.ssh/id_ed25519
        accept_hostkey: yes

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'
 
    - name: Copy Upstart configuration
      template: src=hello-world.upstart.j2 dest=/etc/init/hello-world mode=a+x
 
    - name: Make sure the server is running
      ansible.builtin.shell: sh /etc/init/hello-world &

    - name: Copy Nginx site
      template: src=hello-world.nginx.j2 dest=/etc/nginx/sites-enabled/hello-world
      notify:
        - restart nginx

    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
