- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: git@github.com:lbarzi/Hello_World.git
      repository_path: /home/vagrant/Hello_World

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python3-pip
        - nginx

    - name: Clone repository
      git:
        repo: "git@github.com:lbarzi/Hello_World.git"
        dest: /home/vagrant/Hello_World
        key_file: /home/vagrant/.ssh/id_ed25519
        accept_hostkey: yes

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'
 
    - name: Copy Upstart configuration
      template: src=hello-world.upstart.j2 dest=/etc/init/hello-world.conf

    - name: Fire up the server
      service: name=hello-world state=started
